updates script

diff --git a/.github/workflows/checks-edited-folders.yml b/.github/workflows/checks-edited-folders.yml
--- a/.github/workflows/checks-edited-folders.yml
+++ b/.github/workflows/checks-edited-folders.yml
@@ -18,31 +18,32 @@ jobs:
       - uses: actions/checkout@v2
       - name: Checks Working Folders
         run: |
-          echo 'Hello World'
+          echo 'Get updated filed'
           has_edited_chat_application=false
           has_edited_chat_backend=false
           git diff --name-only origin/main... > files.txt
-          echo files.txt
+          echo '----- ----- -----'
+          cat files.txt
+          echo '----- ----- -----'
 
           while IFS= read -r file
           do
-            echo $file
-            if [[ $file != chat_application/** ]]; then
+          if [[ $file != chat-application/** ]]; then
               has_edited_chat_application=true
-            elif [[ $file != chat_backend/** ]]; then
+          elif [[ $file != chat-backend/** ]]; then
               has_edited_chat_backend=true
-            fi
+          fi
           done < files.txt
 
-          if [ "$has_edited_chat_application" = true] ; then
-            echo 'You've edited chat_application'
+          if [ "$has_edited_chat_application" = true ] ; then
+          echo "You've edited chat-application/"
           fi
 
-          if [ "$has_edited_chat_backend" = true] ; then
-            echo 'You've edited chat_backend'
+          if [ "$has_edited_chat_backend" = true ] ; then
+          echo "You've edited chat-backend/"
           fi
 
-          if [ "$has_edited_chat_application" = true && "$has_edited_chat_backend" = true] ; then
-            echo 'You cannot edit chat_application and chat_backend!'
-            exit 1
+          if [ "$has_edited_chat_application" = true ] && [ "$has_edited_chat_backend" = true ] ; then
+          echo 'You cannot edit chat-application/ and chat-backend/!'
+          exit 1
           fi
